### ISSUE TITLE
the README should include clear steps on how to install the addon

### ISSUE THREAD

**Issue by pigeonflight** [collective/volto-dropdownmenu#14]
From what I'm reading, It doesn't look like mrsdeveloper is the recommended approach to managing addons.
[It seems I need to use `package.json`](https://training.plone.org/5/mastering-plone/volto_addon.html)
It would be helpful to include instructions on how to do this directly within the README

**Comment by arky** [comment]
I struggled with it until I was pointed to Volto documentation.
